package org.geki.knime.excelformreader;

import java.io.File;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

import org.geki.knime.excelformreader.ExcelFormReaderSettings.InputMode;
import org.geki.knime.excelformreader.ExcelFormReaderSettings.OutputFormat;
import org.geki.knime.excelformreader.domain.FormDefinition;
import org.geki.knime.excelformreader.domain.ReadingMode;
import org.geki.knime.excelformreader.excel.ExcelFormExtractor;
import org.geki.knime.excelformreader.excel.WorkbookIterator;
import org.geki.knime.excelformreader.output.LabelOutputBuilder;
import org.geki.knime.excelformreader.output.LongOutputBuilder;
import org.geki.knime.excelformreader.output.OutputSpecFactory;
import org.geki.knime.excelformreader.output.WideOutputBuilder;
import org.geki.knime.excelformreader.excel.ExcelFormExtractor.CellExtractionResult;
import org.knime.core.data.DataRow;
import org.knime.core.data.DataTableSpec;
import org.knime.core.node.BufferedDataContainer;
import org.knime.core.node.BufferedDataTable;
import org.knime.core.node.CanceledExecutionException;
import org.knime.core.node.ExecutionContext;
import org.knime.core.node.ExecutionMonitor;
import org.knime.core.node.InvalidSettingsException;
import org.knime.core.node.NodeLogger;
import org.knime.core.node.NodeModel;
import org.knime.core.node.NodeSettingsRO;
import org.knime.core.node.NodeSettingsWO;
import org.knime.core.node.port.PortType;

public class ExcelFormReaderNodeModel extends NodeModel {

    private static final NodeLogger LOGGER =
        NodeLogger.getLogger(ExcelFormReaderNodeModel.class);

    private final ExcelFormReaderSettings m_settings = new ExcelFormReaderSettings();

    public ExcelFormReaderNodeModel() {
        super(new PortType[]{BufferedDataTable.TYPE},
              new PortType[]{BufferedDataTable.TYPE,
                             BufferedDataTable.TYPE});
    }

    /**
     * TODO: Output spec mismatch warning
     *
     * KNIME shows a "DataSpec generated by configure does not
     * match spec after execution" warning because configure()
     * returns a partial spec (provenance columns only in WIDE
     * mode) while execute() builds the full spec including all
     * field columns from the form definition table.
     *
     * Root cause: the form definition is an input TABLE — its
     * actual content (field names and types) is not available
     * at configure() time, only the table spec (column names)
     * is known. Since field names become output column names,
     * the full output spec cannot be determined at configure().
     *
     * Potential fixes:
     * A) Accept a file path for the definition table in the
     *    dialog and read it at configure() time to build the
     *    full spec — breaks the "definition via input port"
     *    design principle.
     * B) Use a PortObjectSpec subclass that carries field
     *    mapping metadata — requires custom port type.
     * C) Live with the warning — the node is functionally
     *    correct, the warning is cosmetic only.
     *
     * Current decision: Option C (accepted).
     * Revisit if KNIME Hub validation rejects the node.
     */
    @Override
    protected DataTableSpec[] configure(final DataTableSpec[] inSpecs)
            throws InvalidSettingsException {
        if (inSpecs[0] == null) {
            throw new InvalidSettingsException("Form definition table is not connected");
        }

        final InputMode mode = m_settings.getInputMode();
        final String path = mode == InputMode.SINGLE_FILE
            ? m_settings.getFilePath()
            : m_settings.getFolderPath();
        if (path == null || path.trim().isEmpty()) {
            throw new InvalidSettingsException(
                "No " + (mode == InputMode.SINGLE_FILE ? "file" : "folder") + " path configured");
        }

        final FormDefinition definition = FormDefinition.fromSpec(inSpecs[0]);

        final DataTableSpec port0Spec;
        if (m_settings.getOutputFormat() == OutputFormat.WIDE) {
            port0Spec = OutputSpecFactory.createWideSpec(definition,
                m_settings.isIncludeSourceFilename(),
                m_settings.isIncludeSheetName(),
                m_settings.isIncludeLabelFields(),
                m_settings.isIncludeFormatCondition(),
                m_settings.isIncludeValidationType());
        } else {
            port0Spec = OutputSpecFactory.createLongSpec(
                m_settings.isIncludeSourceFilename(),
                m_settings.isIncludeSheetName(),
                m_settings.isIncludeFormatCondition(),
                m_settings.isIncludeValidationType());
        }

        final DataTableSpec port1Spec = OutputSpecFactory.createLabelSpec(
            m_settings.isIncludeSourceFilename(),
            m_settings.isIncludeSheetName(),
            m_settings.isIncludeFormatCondition(),
            m_settings.isIncludeValidationType());

        return new DataTableSpec[]{port0Spec, port1Spec};
    }

    @Override
    protected BufferedDataTable[] execute(final BufferedDataTable[] inData,
                                           final ExecutionContext exec) throws Exception {
        final FormDefinition definition = FormDefinition.fromDataTable(inData[0]);

        final boolean wide = m_settings.getOutputFormat() == OutputFormat.WIDE;
        final boolean includeLabelFields = m_settings.isIncludeLabelFields();
        final boolean outputLabelPort = m_settings.isOutputLabelPort();

        final DataTableSpec port0Spec = wide
            ? OutputSpecFactory.createWideSpec(definition,
                m_settings.isIncludeSourceFilename(),
                m_settings.isIncludeSheetName(),
                includeLabelFields,
                m_settings.isIncludeFormatCondition(),
                m_settings.isIncludeValidationType())
            : OutputSpecFactory.createLongSpec(
                m_settings.isIncludeSourceFilename(),
                m_settings.isIncludeSheetName(),
                m_settings.isIncludeFormatCondition(),
                m_settings.isIncludeValidationType());

        final BufferedDataContainer container = exec.createDataContainer(port0Spec);

        final DataTableSpec port1Spec = OutputSpecFactory.createLabelSpec(
            m_settings.isIncludeSourceFilename(),
            m_settings.isIncludeSheetName(),
            m_settings.isIncludeFormatCondition(),
            m_settings.isIncludeValidationType());
        final BufferedDataContainer labelContainer = exec.createDataContainer(port1Spec);

        final WideOutputBuilder wideBuilder = wide
            ? new WideOutputBuilder(port0Spec,
                m_settings.isIncludeSourceFilename(),
                m_settings.isIncludeSheetName(),
                includeLabelFields,
                m_settings.isIncludeFormatCondition(),
                m_settings.isIncludeValidationType())
            : null;
        final LongOutputBuilder longBuilder = !wide
            ? new LongOutputBuilder(port0Spec,
                m_settings.isIncludeSourceFilename(),
                m_settings.isIncludeSheetName(),
                includeLabelFields,
                m_settings.isIncludeFormatCondition(),
                m_settings.isIncludeValidationType())
            : null;
        final LabelOutputBuilder labelBuilder = new LabelOutputBuilder(port1Spec,
            m_settings.isIncludeSourceFilename(),
            m_settings.isIncludeSheetName(),
            m_settings.isIncludeFormatCondition(),
            m_settings.isIncludeValidationType());

        final ExcelFormExtractor extractor = new ExcelFormExtractor(m_settings);

        final InputMode inputMode = m_settings.getInputMode();
        final String path = inputMode == InputMode.SINGLE_FILE
            ? m_settings.getFilePath()
            : m_settings.getFolderPath();
        final ReadingMode readingMode = inputMode == InputMode.FOLDER
            ? ReadingMode.FOLDER
            : ReadingMode.SINGLE_FILE;

        final boolean processManySheets = inputMode == InputMode.FOLDER
            ? m_settings.getFolderManySheets()
            : m_settings.getFileManySheets();

        final boolean includeHiddenSheets;
        if (inputMode == InputMode.FOLDER) {
            includeHiddenSheets = m_settings.getFolderManySheets()
                ? m_settings.isFolderIncludeHiddenSheets()
                : m_settings.isFolderSingleIncludeHiddenSheets();
        } else if (m_settings.getFileManySheets()) {
            includeHiddenSheets = m_settings.isFileIncludeHiddenSheets();
        } else {
            includeHiddenSheets = m_settings.isFileSingleIncludeHiddenSheets();
        }

        long rowIndex = 0;
        long labelRowIndex = 0;
        try (WorkbookIterator iterator = new WorkbookIterator(
                Paths.get(path),
                readingMode,
                processManySheets,
                inputMode == InputMode.FOLDER
                    ? m_settings.getFolderSheetSelection()
                    : m_settings.getFileSheetSelection(),
                inputMode == InputMode.FOLDER
                    ? m_settings.getFolderSheetName()
                    : m_settings.getFileSheetName(),
                inputMode == InputMode.FOLDER
                    ? m_settings.getFolderSheetPosition()
                    : m_settings.getFileSheetPosition(),
                inputMode == InputMode.SINGLE_FILE
                    ? m_settings.getFileSheetFilterMode()
                    : m_settings.getFolderSheetFilterMode(),
                inputMode == InputMode.SINGLE_FILE
                    ? m_settings.getFileSheetFilterNames()
                    : m_settings.getFolderSheetFilterNames(),
                includeHiddenSheets,
                m_settings.isRecursive(),
                m_settings.isIncludeHiddenFiles(),
                m_settings.isIncludeHiddenFolders(),
                m_settings.isFilterByExtension(),
                m_settings.getFileExtensions())) {

            while (iterator.hasNext()) {
                final WorkbookIterator.Entry entry = iterator.next();

                exec.checkCanceled();
                exec.setMessage("Reading sheet '" + entry.sheetName
                    + "' from " + entry.filePath.getFileName());

                final Map<String, CellExtractionResult> results =
                    extractor.extract(entry.sheet, definition, entry.workbook);

                final String filePath = entry.filePath.toString();
                final String sheetName = entry.sheetName;

                if (wide) {
                    final DataRow row = wideBuilder.buildRow(
                        filePath, sheetName, results, definition, rowIndex++);
                    container.addRowToTable(row);
                } else {
                    final List<DataRow> rows = longBuilder.buildRows(
                        filePath, sheetName, results, definition, rowIndex);
                    rows.forEach(container::addRowToTable);
                    rowIndex += rows.size();
                }

                if (outputLabelPort) {
                    final List<DataRow> labelRows = labelBuilder.buildRows(
                        filePath, sheetName, results, definition, labelRowIndex);
                    labelRows.forEach(labelContainer::addRowToTable);
                    labelRowIndex += labelRows.size();
                }
            }
        }

        container.close();
        labelContainer.close();
        return new BufferedDataTable[]{container.getTable(), labelContainer.getTable()};
    }

    @Override
    protected void saveSettingsTo(final NodeSettingsWO settings) {
        m_settings.saveSettings(settings);
    }

    @Override
    protected void loadValidatedSettingsFrom(final NodeSettingsRO settings)
            throws InvalidSettingsException {
        m_settings.loadSettings(settings);
    }

    @Override
    protected void validateSettings(final NodeSettingsRO settings)
            throws InvalidSettingsException {
        m_settings.validateSettings(settings);
    }

    @Override
    protected void reset() {}

    @Override
    protected void loadInternals(final File nodeInternDir, final ExecutionMonitor exec)
            throws CanceledExecutionException {}

    @Override
    protected void saveInternals(final File nodeInternDir, final ExecutionMonitor exec)
            throws CanceledExecutionException {}
}
